
name: CI - Build, Test, and Lint

# This will trigger the workflow on pull requests and merge to the integration branch
on:
  pull_request:
    branches: [ "integration" ]
    types: [opened, reopened, closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Commented out steps because of missing scripts in package.json and lint errors

    #- name: Run lint
    #  run: npm run lint
    
    #- name: Build
    #  run: npm run build

    #- name: Run tests
    #  run: npm test
